# Generated by Django 6.1.1 on 2026-09-29 23:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160, verbose_name="Titre de l'article")),
                ('rubrique', models.CharField(choices=[('PREVENTION', 'Prévention'), ('SYMPTOMES', "Symptômes et signes d'alerte"), ('DEPISTAGE', 'Dépistage et son importance')], max_length=15)),
                ('contenu', models.TextField(verbose_name='Texte en langage simple')),
                ('source', models.CharField(max_length=200, verbose_name='Source officielle (ex: OMS)')),
                ('mis_a_jour_le', models.DateField(verbose_name='Date de la source')),
            ],
        ),
        migrations.CreateModel(
            name='Autopalpation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date de l'autopalpation")),
                ('sein', models.CharField(choices=[('GAUCHE', 'Sein Gauche'), ('DROIT', 'Sein Droit'), ('LES_DEUX', 'Les Deux Seins')], max_length=10)),
                ('observation', models.CharField(choices=[('RAS', 'Rien de particulier'), ('MASSE', 'Boule ou masse perçue'), ('DOULEUR', 'Douleur inhabituelle'), ('ECOULEMENT', 'Écoulement du mamelon'), ('PEAU', 'Modification de la peau ou du mamelon'), ('AUTRE', 'Autre observation')], max_length=15)),
                ('notes', models.TextField(blank=True, verbose_name='Précisions libres')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisatrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopalpations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=120, verbose_name='Structure (ex: CHU de Bogodogo)')),
                ('lieu', models.CharField(max_length=160, verbose_name='Adresse ou quartier')),
                ('date', models.DateField(verbose_name='Jour du dépistage')),
                ('heure', models.TimeField(verbose_name='Heure de début')),
                ('communique', models.FileField(upload_to='communiques/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Communiqué officiel (5 Mo max)')),
                ('validee', models.BooleanField(default=False)),
                ('publiee_le', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('UTILISATRICE', 'Utilisatrice'), ('FOURNISSEUR', 'Fournisseur')], default='UTILISATRICE', max_length=15)),
                ('structure', models.CharField(blank=True, max_length=150, verbose_name="Nom de l'hôpital ou association")),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Contact du fournisseur')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
